name: ablon-tlpp-unittest
version: 0.0.2
synopsis: Simplest and Lightest unit test framework for TLPP
maintainer: Rodrigo Antonio Godinho <rodrigo.antonio@totvs.com.br>
license: MIT
repository: https://github.com/totvs/ablon-tlpp-unittest
category: test
type: source

exposed-includes:

library:
    source-dirs: src
tests:
    source-dirs: test
    dependencies: tlpp-core
        